# Generated by Django 3.0.3 on 2020-03-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='cTime',
            field=models.DateTimeField(null=True),
        ),
    ]
