# Generated by Django 3.0.3 on 2020-03-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2api', '0002_auto_20200320_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='cTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
