# Generated by Django 3.0.3 on 2020-03-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2api', '0003_auto_20200322_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='cTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
