# Generated by Django 3.0.3 on 2020-04-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2api', '0004_auto_20200323_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmoney', models.CharField(max_length=20)),
                ('ctime', models.CharField(max_length=20)),
                ('cclass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cget', models.CharField(max_length=20)),
                ('csay', models.CharField(max_length=20)),
            ],
        ),
    ]
