# Generated by Django 3.0.3 on 2020-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2api', '0005_money_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='ccid',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='reminder',
            name='cid',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='money',
            name='cmoney',
            field=models.IntegerField(),
        ),
    ]
