# Generated by Django 3.0.3 on 2020-04-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2api', '0006_auto_20200406_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='ccid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='cid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
