# Generated by Django 3.0.3 on 2020-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2api', '0007_auto_20200406_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='ctime',
        ),
        migrations.AddField(
            model_name='money',
            name='cday',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='money',
            name='cmonth',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='money',
            name='cyear',
            field=models.CharField(default='', max_length=4),
        ),
    ]
