# Generated by Django 3.0.3 on 2020-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2api', '0008_auto_20200406_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('switch', models.CharField(max_length=20)),
            ],
        ),
    ]
