# Generated by Django 3.0.3 on 2020-04-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2api', '0009_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='switch',
            field=models.CharField(default='', max_length=20),
        ),
    ]
